// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cobaef.Models;

namespace cobaef.Migrations.Contoh03
{
    [DbContext(typeof(Contoh03Context))]
    partial class Contoh03ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cobaef.Models.Product", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProductName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductCode");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("cobaef.Models.ProductUom", b =>
                {
                    b.Property<string>("ProductCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UomCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ProductCode", "UomCode");

                    b.HasIndex("UomCode");

                    b.ToTable("ProductUoms");
                });

            modelBuilder.Entity("cobaef.Models.Uom", b =>
                {
                    b.Property<string>("UomCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UomName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UomCode");

                    b.ToTable("Uoms");
                });

            modelBuilder.Entity("cobaef.Models.ProductUom", b =>
                {
                    b.HasOne("cobaef.Models.Product", "Product")
                        .WithMany("ProductUoms")
                        .HasForeignKey("ProductCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cobaef.Models.Uom", "Uom")
                        .WithMany("ProductUoms")
                        .HasForeignKey("UomCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
