// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using cobaef.Models;

namespace cobaef.Migrations.Contoh04
{
    [DbContext(typeof(Contoh04Context))]
    [Migration("20200726073933_Contoh04_createdb")]
    partial class Contoh04_createdb
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("cobaef.Models.Supplier", b =>
                {
                    b.Property<string>("SupplierCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SupplierName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SupplierCode");

                    b.ToTable("Suppliers");
                });

            modelBuilder.Entity("cobaef.Models.SupplierAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Street")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SupplierCode")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("SupplierCode")
                        .IsUnique()
                        .HasFilter("[SupplierCode] IS NOT NULL");

                    b.ToTable("SupplierAddresses");
                });

            modelBuilder.Entity("cobaef.Models.SupplierAddress", b =>
                {
                    b.HasOne("cobaef.Models.Supplier", "Supplier")
                        .WithOne("Address")
                        .HasForeignKey("cobaef.Models.SupplierAddress", "SupplierCode");
                });
#pragma warning restore 612, 618
        }
    }
}
